### ISSUE TITLE
Prevent unnecessary requests when accessing fields that are not set

### ISSUE THREAD

**Issue by rensbaardman** [joalla/discogs_client#106]
When accessing fields which are not set in the Discogs database (such as the `real_name` for an artist which is not a person), this can lead to an unnecessary extra request.

Take this example, where we first access the name, triggering the first request. Then we access the `real_name` (which is not set for The Beatles, since it is not a person), triggering the second request to the same endpoint.
```python
import discogs_client
import logging
logging.basicConfig(level=logging.DEBUG)

client = discogs_client.Client('ExampleApplication/0.1')
artist = client.artist(82730)
print(f'{artist.name=}')
print(f'{artist.real_name=}')
```
This results in the following:
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.discogs.com:443
DEBUG:urllib3.connectionpool:https://api.discogs.com:443 "GET /artists/82730 HTTP/1.1" 200 None
artist.name='The Beatles'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.discogs.com:443
DEBUG:urllib3.connectionpool:https://api.discogs.com:443 "GET /artists/82730 HTTP/1.1" 200 None
artist.real_name=None
```

I think the problem lies in the fact that the Discogs API does not return a value (e.g. `None`) when it is not set. And `discogs_client` only sets/updates a value when it is explicitly returned by the API.

I can see two solutions:
- specifying which fields can be returned when fetching from a specific endpoint, and then setting them to `None` (or similar) when they are not returned
- cache the response of the first request

**Comment by AnssiAhola** [comment]
Hi @rensbaardman 

Thanks for filing an issue for this.

The current implementation checks for the given key/property in "cached" data from the first request.
If it isn't found, the client tries to refresh and fetch the data again using the resource url.
If STILL it isn't found then that key/property will be marked as a "known invalid key".

https://github.com/joalla/discogs_client/blob/31b7936a649cfe08fedc962bf0e537650615c191/discogs_client/models.py#L219-L243

One solution might be that we check if the original endpoint matches the resource url of that object, then we can assume that refreshing wont suddenly populate that field and just return Null/default value, thus preventing the extra/unnecessary request.
Problem with this is to figure out how/where to check for the original endpoint.

I can look into this at some point this week. That is if you don't want to take a crack at it?

Cheers!
-Anssi

**Comment by JOJ0** [comment]
@rensbaardman have a look at the linked PR. @AnssiAhola might have improved the request behaviour. It would help us a lot if you find the time to test the branch. If you need help with installing from that feature branch I can help. Thanks and all the best!

**Comment by rensbaardman** [comment]
Thanks for taking the time to implement a solution! This solves the problem I originally had, so that is great.

Unfortunately, I think the implementation has a bug: since a new request will look at the `previous_request` from the `client`, this means that recreating the same artist won't get the correct data:

```python
import discogs_client
import logging
logging.basicConfig(level=logging.DEBUG)

client = discogs_client.Client('ExampleApplication/0.1')

artist = client.artist(82730)
print(f'{artist.name=}')

same_artist = client.artist(82730)
print(f'{same_artist.name=}')
```
returns 
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.discogs.com:443
DEBUG:urllib3.connectionpool:https://api.discogs.com:443 "GET /artists/82730 HTTP/1.1" 200 1789
artist.name='The Beatles'

same_artist.name=None
```

As you see, the second time we try to fetch the artist, this won't trigger a new download since the `client.previous_request` already points to this artists endpoint.

I think changing `self.previous_request = client.previous_request` to simply `self.previous_request = None` should fix this: 

https://github.com/joalla/discogs_client/blob/27663e3dcd249dba2ebf69a9685e5a9194fd0d91/discogs_client/models.py#L191

And I believe saving the `previous_request` in `client` has no purpose now, so this should be fine? (in which case, probably better to remove that part)

**Comment by AnssiAhola** [comment]
Good catch! Fixed it and removed the `previous_request` from client.
Also added a simple test to prevent stuff like this from slipping through in the future :sweat_smile:
