### ISSUE TITLE
Accessing release catalog number

### ISSUE THREAD

**Issue by JOJ0** [joalla/discogs_client#74]
### Discussed in https://github.com/joalla/discogs_client/discussions/37

<div type='discussions-op-text'>

<sup>Originally posted by **masquinongy** February  9, 2021</sup>
Hey, how do I get the catalog number for a release? Thanks.</div>

It should be possible to access the catalog number of an release like so:
`myrelease.labels[n].catno`

Currently it's only possible to access it like that:

`myrelease.labels[n].fetch("catno")`

or

`myrelease.labels[n].data["catno"]`

**Comment by bodeni** [comment]
Hi! And how do I get the label name for a release? 

KeyError: 'label':
`myrelease.labels[n].data["label"]`

**Comment by 0todd0000** [comment]
If there is just one label, then use:

```python
label_name = release.labels[0].data['name']
```

To get all label names, use a list comprehension:

```python
label_names = [x.data['name'] for x in release.labels]
```

<br>
<br>

If you print ` release.labels[0].data` this will be obvious.

```python
print( release.labels[0].data )
```

yields, for example:
```
{'name': 'London Records', 'catno': 'AMCE-6104/5', 'entity_type': '1', 'entity_type_name': 'Label', 'id': 1060, 'resource_url': 'https://api.discogs.com/labels/1060', 'thumbnail_url': 'https://img.discogs.com/NxZagPxZX5GZncQkq-oh3uIcmSg=/fit-in/553x553/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/L-1060-1589194147-2980.jpeg.jpg'}
```
