### ISSUE TITLE
Problems with OAuth

### ISSUE THREAD

**Issue by bernd-wechner** [joalla/discogs_client#75]
I'm a tad stuck. Following the doc:

```
import discogs_client

ConsumerKey = "my_app_key"
ConsumerSecret = "my_app_secret"

client = discogs_client.Client("puddletag", consumer_key=ConsumerKey, consumer_secret=ConsumerSecret)
auth_url = client.get_authorize_url()
```

works wonderfully returning:

```
('my_request_token', 'my_request_secret', 'https://www.discogs.com/oauth/authorize?oauth_token=my_request_token')
```

after which the docs here:

https://python3-discogs-client.readthedocs.io/en/latest/authentication.html#oauth-authentication

fail me a little. I'm not sure what do do with `my_request_secret`, but I can see `my_request_token` is in the URL.

if I paste that URL into my browser, I actually get  a cod. Discogs returns:

```
Authorization successful

If the application asks you for a code, enter the following:

my_code

You can now close this window.
```

But if I now run this:
```
token = client.get_access_token(my_code)
```

An exception is raised with `'400: Invalid response from access token URL.'`

What am I doing wrong here? And is there something missing from the docs that might have helped me fix this?

**Comment by bernd-wechner** [comment]
Actually, I have it working and indeed I suspect an improvement to t docs would have saved me much time. And I wonder if I can get confirmation of my conclusions and I'd be happy to PR a doc improvement. 

Here is my conclusion:

`client.get_authorize_url()` returns a `(token, secret)` tuple. This has lasting life. If I save that. And now I do:

```
client = discogs_client.Client("puddletag",
                               consumer_key=consumer_key,
                               consumer_secret=consumer_key,
                               token=request_token,
                               secret=request_secret)
```
where `consumer_key` and `consumer_secret` are for my app from the Developer settings at discogs, and request_toke and request_secret are the token and secret returned by client.get_authorize_url(), the I am authorized from that point on. 

None of that came across from the docs.  

Have I worked this out correctly? As a noob to Oauth.

**Comment by AnssiAhola** [comment]
Hey @bernd-wechner
That is indeed correct, theres this line in the docs that kind of hints at the token and secret being something to cherish and hold on to once you get them, although it could definately be more clearly worded 😄 
```
You can also supply your OAuth token and token secret if you already have them saved, as so:
```
```python
d = discogs_client.Client(
    'my_user_agent/1.0',
    consumer_key='my_consumer_key',
    consumer_secret='my_consumer_secret',
    token=u'my_token',
    secret=u'my_token_secret'
)
```
If for example your app is used by others, this way your app can be authorized to access/use users data in discogs
Hope that clears things a little 😅 

Cheers!
Anssi

**Comment by JOJ0** [comment]
Hi @bernd-wechner, if you want to file a PR rewording this a little we would definitely appreciate it.

By any chance, are you the dev/maintainer of puddletag?

**Comment by bernd-wechner** [comment]
A PR to the doc?

No, not a formal dev/maintainer of puddletag? An historic fan (mp3tag lover in my Windows days, then switching to Linux and finding puddletag (a FOSS clone of mp3tag which is FNOSS - Free NOT Open Source Software) I was using it. It fell short on a few fronts (being FOSS ;-)) and I looked into fixing bits, but it was Python 2.7 at a time when Python 3 was already the norm and so had a Python 2 to 3 migration issue open with no action and I waited for that to complete and went into hiatus (pursuing other projects of which there is always a long competing list). I returned to a little audio tagging this year and tried puddletag again, and it was now Python3, so I've started fixing the bits I need. So I've PRed it a few times recently and it was well received, fixed one tag source and I am working on the discogs tagsource now (it broke a long time ago) but am still testing the PR waters.

Rule 1 of FOSS contrib: keep early PRs very small and incremental to facilitate review and merge decisions and avoid over-investing any time or energy into a project that proves stagnant (no response to PRs) or highbrow (maintained by well, let's just say demanding and/or challenging people - not that IT has any of those ;-)).  And that's where I'm at, at puddletag. Even so I'm not far off 3rd top contributor so it's not a huge project:

https://github.com/puddletag/puddletag/graphs/contributors

**Comment by JOJ0** [comment]
yeah a pr against https://github.com/joalla/discogs_client/blob/master/docs/source/authentication.md would be great :-)

haha thanks for sharing your story. funilly enough I also used mp3tag for a very long time and recall there wasnt really a good alternative back then. most of all the discogs tagging feature was there and even working very well. even when i used macos and linux mainly i kept a win7 vm almost only for mp3tag.

i came across puddletag recently because of reading docs of mutagen and catched puddletag in the "tools that use mutagen" section and thought "if that would have been there back then", finally a promising alternative. and actually i came across mutagen in detail only because of contributing to beets. appreciate your efforts on contributing to good FOSS tagging solutions 💪🏽

**Comment by JOJ0** [comment]
@bernd-wechner we just merged some additions to the docs about building the sphinx docs. Probably not strictly necessary to your rewording changes but just in case you would like to see how the rendered docs will look like when merged, here is what you need to do to build them locally on your machine: https://python3-discogs-client.readthedocs.io/en/latest/writing_docs.html#install-prerequisites

**Comment by JOJ0** [comment]
@bernd-wechner I'm closing since I dont know what could be improved in the docs. Please feel free to reopen and drop me a line and I'll handle committing into the docs. Thanks!

**Comment by bernd-wechner** [comment]
> @bernd-wechner I'm closing since I dont know what could be improved in the docs. Please feel free to reopen and drop me a line and I'll handle committing into the docs. Thanks!

Up front humble apologies for the enormous delay. I clearly have my finger in too many pies ;-). But I'm on one of my too all too rare, tab clean up sessions ...  where I find tabs still open from ...  yep, a year ago. So under the principles of GTD, I triage quickly and decide to formally todo it or just do it or just close it. 

On this one I reviewed now, and this:

https://python3-discogs-client.readthedocs.io/en/latest/authentication.html#oauth-authentication

does indeed explain what I needed and isn't bad at all!

Really the only way I'd improve that, and it's subjective, not everyone will have the same style here (though I do humbly submit I collected min writing software manuals and help over years) is where is written:

---
3. Get authorization URL
'''python
d.get_authorize_url()
'''
This will return a tuple with the request token, request secret, and the authorization URL that your user needs to visit to accept your app’s request to sign in on their behalf.
---

I would make it more explicit:

---
3. Get authorization URL
'''python
(request_token, request_secret, auth_URL) = d.get_authorize_url()
'''
where `request_token` and `request_secret` are used when instantiating `discogs_client.Client()` (teh arguments `token`, and `secret` respectively) and you need to open auth_URL in a browser and manually accept the app's request to sign in.
---
Assuming that's right - I haven't tested and don't have my IDE open ;-). I'm just sharing my thoughts on how it might better express how to get started.

**Comment by JOJ0** [comment]
If you find time for test and that PR that would indeed be wonderful! Appreciate not forgetting after that long time. Your tabs are patient it seems :-) Thanks again
