### ISSUE TITLE
Add docs chapter: How to build the sphinx docs.

### ISSUE THREAD

**Issue by JOJ0** [joalla/discogs_client#76]
somewhere around the "Contribution" chapters

**Comment by prcutler** [comment]
I can help this too - I'll need to do this tomorrow and see if I can document the steps after I update the chapter

**Comment by prcutler** [comment]
I should have created a new branch separate from my other PR, but I forgot.  Here is a new page on writing docs: https://github.com/joalla/discogs_client/commit/f62506ee6caa0e71a050e0b0ef2282aeb23ff549 which is in the same PR as my other work.  (Sorry!)

Please review - I already caught a few mistakes.  If you catch any, I promise to turn the fixes in faster this time.  😄 

I may have gone a little overboard - I linked to Github's page on forking and creating PRs and gave it a high level overview.

Thanks.

--P
