### ISSUE TITLE
Collection items by release

### ISSUE THREAD

**Issue by raratiru** [joalla/discogs_client#90]
Feature request for the next steps, when a collection "grows up"!

Trying to make ends meet with collection internals, this [line of the docs](https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection) helped a lot:

> Because it’s possible to own more than one copy of a release, each with its own notes, grading, and so on, each instance of a release in a folder has an instance ID.

### Concern
A "grown up" collection, will be more difficult to [iterate and delete](https://python3-discogs-client.readthedocs.io/en/latest/fetching_data.html#removing-a-release-from-a-collection-folder). 

### Possible solution
The API [provides](https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection-items-by-release) a url which returns only the "collection items" of a `release_id`.

Each result, includes the `instance_id` which is crucial [for the deletion process](https://www.discogs.com/developers/#page:user-collection,header:user-collection-delete-instance-from-folder).

### Implementation

If implemented, a user could do:

```python
folder = me.collection_folders[0]
release_in_collection = folder.release(1234567)

# Option 1
for instance in release_in_collection:
    if criterion_met: 
        folder.remove_release(release_in_collection, instance=instance['instance_id'])

#Option 1 + 1
folder.remove_release(release_in_collection, instance="__all__")

# Power Option
folder.remove_release(
    release_id, 
    instances=[release_in_collection[0]['instance_id'], release_in_collection[1]['instance_id']],
)  # Remove all if instances is None
```

**Comment by AnssiAhola** [comment]
Hi @raratiru 
Thank for another feature request!

If I understand correctly that API point you linked to returns a list of what in this case would be `CollectionItemInstance`s ?
But in this case only those for that specific release/release_id?

Considering the `remove_release` method we added in previous PR requires a `CollectionItemInstance`
and we can't just go changing the method signature
would this example suffice?

```python
folder = me.collection_folders[0]
release_instances = folder.release(1234567) # Id prefer something like `get_release_instances` or similar

for instance in release_instances
    if some_criteria is True: 
        folder.remove_release(instance)
```

**Comment by raratiru** [comment]
Thank you indeed for your prompt answer. I just got puzzled by the docs.

Of course it will be great, by all means!
