### ISSUE TITLE
Feature request: index method on collection_folders to get the index using the folder name.

### ISSUE THREAD

**Issue by jayPare** [joalla/discogs_client#93]
Feature request: .index on collection_folders to get the index using the folder name. Maybe there is already a way to do it other than looping through all folders and checking their name attribute, but I'm not really advanced in Python. If there is no other way, I would be glad to at least try to implement this feature and create a pull request for it.

**Comment by AnssiAhola** [comment]
Hey @jayPare 
Could you provide a small code example on how you would use this feature.

I don't think theres an API point that can do this and like you said this can be done by looping through the folders, which isn't ideal I admit.

Feel free to submit a pull request if you come up with something, contributions are always welcome!

Cheers!
-Anssi

**Comment by JOJ0** [comment]
@jayPare since there was no further info on how this could be tackled I'm closing. Feel free to reopen with further ideas. Thanks!
